default_controllers:
    resource:
        path: '../src/Default/Controller/'
        namespace: App\Default\Controller
    type: attribute
person_controllers:
    resource: 
        path: '../src/Person/Controller/'
        namespace: App\Person\Controller
    type: attribute